general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 5 Minutes: Dim Screen
listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# 10 Minutes: Lock Screen
listener {
    timeout = 600
    on-timeout = loginctl lock-session
}

# 15 Minutes: Suspend to RAM
listener {
    timeout = 900
    on-timeout = systemctl suspend
}

# 50 Minutes: Suspend to SSD (Hibernate)
listener {
    timeout = 3000
    on-timeout = systemctl hibernate
}
