exec swayidle -w \
    timeout 150 'brightnessctl -s set 10%' resume 'brightnessctl -r' \
    timeout 300 'swaylock' \
    timeout 600 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
    timeout 1200 'systemctl suspend' \
    timeout 2400 'systemctl hibernate' \
    before-sleep 'swaylock'
